//package classifiers;
//
//Classifier cModel = (Classifier)new REPTree();
//	System.out.print("REPTree           ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new LMT();
//	System.out.print("LMT           ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new J48();
//	System.out.print("J48           ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new NaiveBayes();
//	System.out.print("NaiveBayes            ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new DecisionTable();
//	System.out.print("DecisionTable         ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new PART();
//	System.out.print("PART          ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new Logistic();
//	System.out.print("Logistic          ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new SimpleLogistic();
//	System.out.print("SimpleLogistic            ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new SimpleCart();
//	System.out.print("SimpleCart            ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new SMO();
//	System.out.print("SMO              ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new Ridor();
//	System.out.print("Ridor           ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new RBFNetwork();
//	System.out.print("RBFNetwork            ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new NNge();
//	System.out.print("NNge          ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);
//	cModel = (Classifier)new HyperPipes();
//	System.out.print("HyperPipes            ");
//	doup(cModel, isTrainingSet, fvWekaAttributes);